name: Build on Windows

on:
  push:
    branches: [ win ]

jobs:
  build-win:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node 14
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build:win