name: Build and deploy to GitHub Pages

on:
  push:
    branches: [ win ]

jobs:
  github-pages:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node 14
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build